export const REDIS_COMMANDS: Array<{ cmd: string; hint: string }> = [
  { cmd: "APPEND", hint: "key value" },
  { cmd: "AUTH", hint: "[username] password" },
  { cmd: "CLIENT", hint: "subcommand [args]" },
  { cmd: "CLUSTER", hint: "subcommand [args]" },
  { cmd: "CONFIG", hint: "GET|SET|RESETSTAT parameter [value]" },
  { cmd: "DBSIZE", hint: "" },
  { cmd: "DECR", hint: "key" },
  { cmd: "DECRBY", hint: "key decrement" },
  { cmd: "DEL", hint: "key [key ...]" },
  { cmd: "ECHO", hint: "message" },
  { cmd: "EXISTS", hint: "key [key ...]" },
  { cmd: "EXPIRE", hint: "key seconds" },
  { cmd: "FLUSHALL", hint: "[ASYNC|SYNC]" },
  { cmd: "FLUSHDB", hint: "[ASYNC|SYNC]" },
  { cmd: "GET", hint: "key" },
  { cmd: "HDEL", hint: "key field [field ...]" },
  { cmd: "HGET", hint: "key field" },
  { cmd: "HGETALL", hint: "key" },
  { cmd: "HKEYS", hint: "key" },
  { cmd: "HMGET", hint: "key field [field ...]" },
  { cmd: "HSET", hint: "key field value [field value ...]" },
  { cmd: "HVALS", hint: "key" },
  { cmd: "INCR", hint: "key" },
  { cmd: "INCRBY", hint: "key increment" },
  { cmd: "INFO", hint: "[section]" },
  { cmd: "KEYS", hint: "pattern" },
  { cmd: "LINDEX", hint: "key index" },
  { cmd: "LLEN", hint: "key" },
  { cmd: "LPOP", hint: "key [count]" },
  { cmd: "LPUSH", hint: "key element [element ...]" },
  { cmd: "LRANGE", hint: "key start stop" },
  { cmd: "LREM", hint: "key count element" },
  { cmd: "MGET", hint: "key [key ...]" },
  { cmd: "MSET", hint: "key value [key value ...]" },
  { cmd: "PERSIST", hint: "key" },
  { cmd: "PING", hint: "[message]" },
  { cmd: "PTTL", hint: "key" },
  { cmd: "RENAME", hint: "key newkey" },
  { cmd: "RPUSH", hint: "key element [element ...]" },
  { cmd: "SADD", hint: "key member [member ...]" },
  { cmd: "SCAN", hint: "cursor [MATCH pattern] [COUNT count] [TYPE type]" },
  { cmd: "SCARD", hint: "key" },
  { cmd: "SELECT", hint: "index" },
  { cmd: "SET", hint: "key value [EX seconds | PX ms | NX | XX]" },
  { cmd: "SETEX", hint: "key seconds value" },
  { cmd: "SETNX", hint: "key value" },
  { cmd: "SMEMBERS", hint: "key" },
  { cmd: "SREM", hint: "key member [member ...]" },
  { cmd: "STRLEN", hint: "key" },
  { cmd: "TTL", hint: "key" },
  { cmd: "TYPE", hint: "key" },
  { cmd: "UNLINK", hint: "key [key ...]" },
  { cmd: "ZADD", hint: "key score member [score member ...]" },
  { cmd: "ZCARD", hint: "key" },
  { cmd: "ZRANGE", hint: "key min max [WITHSCORES]" },
  { cmd: "ZREM", hint: "key member [member ...]" },
  { cmd: "ZSCORE", hint: "key member" },
];
